package(default_visibility = [
    "//Sources:__subpackages__",
])

exports_files([
    "LaunchScreen.storyboard",
])

filegroup(
    name = "AppIcon.xcassets",
    srcs = glob(["AppIcon.xcassets/**"]),
)
