load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "SnapKit",
    srcs = glob(["Source/*.swift"]),
    module_name = "SnapKit",
    visibility = ["//visibility:public"],
)
